// Mock Electron preload APIs globally for renderer/React tests
if (typeof window !== 'undefined') {
  window.api = {
    login: async () => ({ success: true, user: { name: 'Test Admin', role: 'admin' } }),
    getCurrentUser: async () => ({ id: 'A1', username: 'admin', role: 'admin' }),
    getStudents: async () => [],
    saveStudent: async () => ({ success: true }),
    deleteStudent: async () => ({ success: true }),
    getTeachers: async () => [],
    saveTeacher: async () => ({ success: true }),
    deleteTeacher: async () => ({ success: true }),
    getClasses: async () => [],
    saveClass: async () => ({ success: true }),
    deleteClass: async () => ({ success: true }),
    getSubjects: async () => [],
    saveSubject: async () => ({ success: true }),
    deleteSubject: async () => ({ success: true }),
    getQuestions: async () => [],
    saveQuestion: async () => ({ success: true }),
    deleteQuestion: async () => ({ success: true }),
    importQuestions: async () => ({ success: true }),
    getAttendance: async () => [],
    saveAttendance: async () => ({ success: true }),
    getAssessments: async () => [],
    saveAssessmentResult: async () => ({ success: true }),
    validateLicense: async () => ({ success: true }),
    getLicenseInfo: async () => ({ key: 'WTA-DEMO-G5-ALL-EXP2028', active: true }),
    getSyncInfo: async () => ({ pendingCount: 0, status: 'synced' }),
    triggerSync: async () => ({ success: true }),
    toggleOnline: async () => ({ success: true, status: 'synced' }),
    getDashboardData: async () => ({
      studentCount: 0,
      facultyCount: 0,
      classCount: 0,
      assessmentCount: 0,
      todayAttendanceRate: 'No Roll Call',
      pendingSyncQueue: [],
      activityLog: [],
      activeClasses: []
    }),
    minimizeWindow: () => {},
    maximizeWindow: () => {},
    closeWindow: () => {},
  };
}
